name: Python GCP Storage

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    environment: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install python packages
      run:
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests
          pip install google-auth
          pip install google-cloud-storage
      env:
        PRIVATE_KEY_ID: ${{ env.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ env.PRIVATE_KEY }}
        CLIENT_EMAIL: ${{ env.CLIENT_EMAIL }}
        CLIENT_ID: ${{ env.CLIENT_ID }}
    - name: execute py script  
      run: python python_weather_storage.py
      