name: Python GitActions

on: push
  #schedule:
  #  - cron:  '*/2 * * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install python packages
      run:
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests
    - name: execute py script
      run: 
        python python_weather.py
    - name: commit and push
      run:
        git config user.name alegodoyp
        git config user.email lelex.g@hotmail.com
        git add -A
        git commit -m "crongenerated"
        git push