name: Python GCP Storage

on: 
  schedule:
    - cron:  '*/2 * * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install python packages
      run:
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests
          pip install google-auth
          pip install google-cloud-storage
    - name: execute py script
      run: 
        python python_weather_storage.py
        git config user.name alegodoyp
        git config user.email lelex.g@hotmail.com
        git add .
        git commit -m "crongenerated storage"
        git push
      env:
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL}}
        CLIENT_ID: ${{ secrets.CLIENT_ID}}